### ISSUE TITLE
peek seems not working

### ISSUE THREAD

**Issue by chiknhed** [PaulStoffregen/AltSoftSerial#11]
It looks like the following code is working for me. 

int AltSoftSerial::peek(void)
{
	uint8_t head, tail;

	head = rx_buffer_head;
	tail = rx_buffer_tail;
	if (head == tail) return -1;
	if (tail + 1 < RX_BUFFER_SIZE)
		return rx_buffer[tail+1];
	else
		return rx_buffer[0];
}

**Comment by PaulStoffregen** [comment]
fixed by https://github.com/PaulStoffregen/AltSoftSerial/commit/23c636bc562312fb213a832a732880e6d7f5bb1f
