### ISSUE TITLE
Multiple instances of AltSoftwareSerial

### ISSUE THREAD

**Issue by pramilo** [PaulStoffregen/AltSoftSerial#14]
Hi

First of all, congratulations on the excellent work you're carrying out both in terms of code and development of Teensy!

I have a requirement for multiple SoftwareSerial instances on an application and having reviewed the AltSoftSerial code, is there any reason why you have locked the pins? (and to some extent ,the timers)?

There doesn't seem to be any particular reason to not allow multiple instances, which would be great given the library's improved performance.

Even just making it as easy to change the Pins as it is for the timers, I think this'd be a great addition.

Another very useful addition would be the possibility to:
- have the library initialized to SEND only or to RECEIVE only
- Implement Half duplex mode (always be in state receiving and flipping only to TX when transmitting, with an optional TransmitEnable pin that goes high when TX is active), mimicking behavior similar to RS485 transceivers.

I believe all of this can be easily implemented and, again, would make for excellent additions (the first and most important being multiple instances).

For the time being I'll stick with NewSoftSerial although I'd rather use AltSoftSerial due to it's better co existence with other code.

Thank you
Pedro

**Comment by PaulStoffregen** [comment]
> I believe all of this can be easily implemented

Then go forth and implement it!
