### ISSUE TITLE
Support for inverse logic 

### ISSUE THREAD

**Issue by pawelsky** [PaulStoffregen/AltSoftSerial#19]
Paul,

are there any plans to introduce support for inverted serial logic (i.e. make use of the _inverse_ parameter of the _AltSoftSerial(uint8_t rxPin, uint8_t txPin, bool inverse = false)_ constructor?

**Comment by PaulStoffregen** [comment]
I'm not planning to work on this.

**Comment by pawelsky** [comment]
Understood. Thanks for quick reply.
