### ISSUE TITLE
void flush() { flushInput(); }  ?

### ISSUE THREAD

**Issue by borisff** [PaulStoffregen/AltSoftSerial#21]
#if ARDUINO >= 100
	size_t write(uint8_t byte) { writeByte(byte); return 1; }
	void flush() { flushOutput(); }
#else
	void write(uint8_t byte) { writeByte(byte); }
	void flush() { flushInput(); }
#10 
Shouln't void flush() { flushInput(); } be void flush() { flushOutput(); } ?

**Comment by PaulStoffregen** [comment]
Before Arduino 1.0, the flush() function discarded input.  This code does the post-1.0 behavior on Arduino 1.0 and later, and the pre-1.0 behavior on old versions.
