### ISSUE TITLE
incompatible with esp8266 architecture(s).

### ISSUE THREAD

**Issue by sleeping1013** [PaulStoffregen/AltSoftSerial#22]
Hi,
I used arduino IDE to code esp8266. (https://github.com/esp8266/Arduino)
when I wrote:
<pre><code>
#include <AltSoftSerial.h>
AltSoftSerial myserial(0,2)
</code></pre>

I couldn't  pass the compiler, and got following error msgs:
WARNING: library AltSoftSerial claims to run on [avr] architecture(s) and may be incompatible with your current board which runs on [esp8266] architecture(s).

It would be helpful if you can provide the compatibility for esp8266, because esp8266 has only one UART and the softwareserial such on communicating with RS232.

Thanks in advance.

Lucas

**Comment by PaulStoffregen** [comment]
I would be happy to merge such code, if anyone contributes it.  But I do not have the time to develop this code.
