### ISSUE TITLE
Possibility to use ATMEGA2560 digital pins 10 and 11

### ISSUE THREAD

**Issue by brunoaduarte** [PaulStoffregen/AltSoftSerial#30]
Hi @PaulStoffregen , is it possible to use pins 10 (RX) and 11(TX) instead of 48, 46 in ATMEGA2560 by modifying "AltSoftSerial_Boards.h" ?

I tried it but it seems not to work. Why ?

**Comment by PaulStoffregen** [comment]
Only timer pins can be used.  The pin numbers correspond to actual hardware resources of the timers.

You can't just put different pin numbers you want into that file.  Well, you can edit the file, but that amounts to nothing more than wishful thinking.
