### ISSUE TITLE
Arduino Mega ADK board, 2x hardware serial comms

### ISSUE THREAD

**Issue by firewood753** [PaulStoffregen/AltSoftSerial#35]
Hello,
I have an Arduino Mega ADK board connected to the PC via the normal square serial connector.

I also have a nordic semiconductor NRF52 board
This is receiving heart rate data from a chest strap via ANT+, and sending the values on its own micro USB serial port @ 115,200 baud, 8 data bits, 1 stop bit, no parity, no flow control.
This is working correctly, using Putty terminal emulator on the PC and plugging the NRF52 directly into a PC USB port, I can see the steam of heart rate data.

Next step is to get the data across to the arduino.
I've connected the NRF52's micro USB port to the Arduino's second serial port (attached), but can't get any data.
Also tried cutting a USB cable in half and connecting to pins 18,19+gnd, but no data.

Can you please help me to get going?
Many thanks,
Phil.
![megaadk](https://cloud.githubusercontent.com/assets/22725638/23264225/8c77c422-f9d8-11e6-9a32-4ae31e371de0.jpg)

**Comment by PaulStoffregen** [comment]
No, this is the wrong place to ask for project help.  Use the Arduino Forum!

Github issue tracker is only for reporting bugs in this software.  Until the problem is confirmed to be a project with this software, use the Arduino Forum.  This is not the place to ask for support or project help.
