### ISSUE TITLE
Issue while using altsoftserial with mpu6050(wire.h)

### ISSUE THREAD

**Issue by Mohit-18** [PaulStoffregen/AltSoftSerial#36]
The data from altsoftserial tx and rx pins are not detected when the program has mpu6050 program which uses wire.h for i2c communication.On removing the mpu6050 code, the program works fine and the data is received properly from bluetooth bl8000l.Arduino Uno board is used with scl and sda pins used for mpu6050 scl and sda.How to obtain data from mpu6050 as well as from bluetooth?

**Comment by PaulStoffregen** [comment]
Use a slower baud rate.
