### ISSUE TITLE
Can we use it on NodeMCU?

### ISSUE THREAD

**Issue by DaniMzT** [PaulStoffregen/AltSoftSerial#64]
Hello. In order to communicate an Arduino UNO and a NodeMCU, I'd like to replace SoftwareSerial by AltSoftSerial. However, I'm afraid AltSoftSerial might not be used on NodeMCU, as I haven't seen specified pins to use it (for example, for Arduino UNO pins 8 and 9 must be used for this library). Could you confirm me if it's possible?

Thank you for the library :)
Best regards

**Comment by PaulStoffregen** [comment]
NodeMCU is not supported
